## Autogenerated from /Users/dickyang/Desktop/Data/celesos.cdt/eosio_llvm/tools/lld/test/Unit/lit.site.cfg.py.in
## Do not edit!

config.llvm_src_root = "/Users/dickyang/Desktop/Data/celesos.cdt/eosio_llvm"
config.llvm_obj_root = "/Users/dickyang/Desktop/Data/celesos.cdt/build/EosioClang-prefix/src/EosioClang-build"
config.llvm_tools_dir = "/Users/dickyang/Desktop/Data/celesos.cdt/build/EosioClang-prefix/src/EosioClang-build/./bin"
config.llvm_libs_dir = "/Users/dickyang/Desktop/Data/celesos.cdt/build/EosioClang-prefix/src/EosioClang-build/./lib"
config.llvm_build_mode = "."
config.lit_tools_dir = ""
config.lld_obj_root = "/Users/dickyang/Desktop/Data/celesos.cdt/build/EosioClang-prefix/src/EosioClang-build/tools/lld"
config.lld_src_root = "/Users/dickyang/Desktop/Data/celesos.cdt/eosio_llvm/tools/lld"
config.lld_libs_dir = "/Users/dickyang/Desktop/Data/celesos.cdt/build/EosioClang-prefix/src/EosioClang-build/./lib"
config.lld_tools_dir = "/Users/dickyang/Desktop/Data/celesos.cdt/build/EosioClang-prefix/src/EosioClang-build/./bin"
config.target_triple = "x86_64-apple-darwin18.2.0"
config.python_executable = "/usr/local/bin/python2.7"

# Support substitution of the tools and libs dirs with user parameters. This is
# used when we can't determine the tool dir at configuration time.
try:
    config.llvm_tools_dir = config.llvm_tools_dir % lit_config.params
    config.llvm_libs_dir = config.llvm_libs_dir % lit_config.params
    config.llvm_build_mode = config.llvm_build_mode % lit_config.params
except KeyError as e:
    key, = e.args
    lit_config.fatal("unable to find %r parameter, use '--param=%s=VALUE'" % (key,key))

# Let the main config do the real work.
lit_config.load_config(config, "/Users/dickyang/Desktop/Data/celesos.cdt/eosio_llvm/tools/lld/test/Unit/lit.cfg.py")
